### ISSUE TITLE
Failed to install packages to new root

### ISSUE THREAD

**Issue by 0pcom** [Portergos/Fork-Portergos-iso#1]
Portergos is, without a doubt, my favorite distribution.
I would so much like to be able to fork it.

I extracted to /home/user/Fork-Portergos and installed archiso, and moved pacstrap and mkarchiso to /usr/bin/

it does a significant amount of work, and then errors out like this...

`[mkarchiso] INFO: Installing packages to 'work/x86_64/airootfs/'...`
`==> Creating install root at work/x86_64/airootfs`
`==> Installing packages to work/x86_64/airootfs`
`:: Synchronizing package databases...`
 `portergos is up to date`
 `antergos is up to date`
 `core is up to date`
 `extra is up to date`
` community is up to date`
` multilib is up to date`
`warning: bash-4.4.023-1 is up to date -- skipping`
`warning: bzip2-1.0.6-7 is up to date -- skipping`
`warning: coreutils-8.29-1 is up to date -- skipping`
`warning: cryptsetup-2.0.4-1 is up to date -- skipping`
`warning: device-mapper-2.02.181-1 is up to date -- skipping`
`warning: dhcpcd-7.0.5b-1 is up to date -- skipping`
`warning: diffutils-3.6-1 is up to date -- skipping`
`warning: e2fsprogs-1.44.3-1 is up to date -- skipping`
`warning: file-5.33-3 is up to date -- skipping`
`warning: filesystem-2018.1-2 is up to date -- skipping`
`warning: findutils-4.6.0-2 is up to date -- skipping`
`warning: gawk-4.2.1-1 is up to date -- skipping`
`warning: gcc-libs-8.2.0-2 is up to date -- skipping`
`warning: gettext-0.19.8.1-2 is up to date -- skipping`
`warning: glibc-2.28-1 is up to date -- skipping`
`warning: grep-3.1-1 is up to date -- skipping`
`warning: gzip-1.9-1 is up to date -- skipping`
`warning: inetutils-1.9.4-5 is up to date -- skipping`
`warning: iproute2-4.17.0-1 is up to date -- skipping`
`warning: iputils-20180629.f6aac8d-2 is up to date -- skipping`
`warning: jfsutils-1.1.15-5 is up to date -- skipping`
`warning: less-530-1 is up to date -- skipping`
`warning: licenses-20171006-1 is up to date -- skipping`
`warning: linux-4.17.13.arch1-1 is up to date -- skipping`
`warning: logrotate-3.14.0-1 is up to date -- skipping`
`warning: lvm2-2.02.181-1 is up to date -- skipping`
`warning: man-db-2.8.4-1 is up to date -- skipping`
`warning: man-pages-4.16-1 is up to date -- skipping`
`warning: mdadm-4.0-1 is up to date -- skipping`
`warning: nano-2.9.8-1 is up to date -- skipping`
`warning: netctl-1.17-1 is up to date -- skipping`
`warning: pacman-5.1.1-1 is up to date -- skipping`
`warning: pciutils-3.6.1-1 is up to date -- skipping`
`error: target not found: pcmciautils`
`warning: perl-5.28.0-1 is up to date -- skipping`
`warning: procps-ng-3.3.15-1 is up to date -- skipping`
`warning: psmisc-23.1-1 is up to date -- skipping`
`warning: reiserfsprogs-3.6.27-1 is up to date -- skipping`
`warning: s-nail-14.9.10-1 is up to date -- skipping`
`warning: sed-4.5-1 is up to date -- skipping`
`warning: shadow-4.5-4 is up to date -- skipping`
`warning: sysfsutils-2.1.0-10 is up to date -- skipping`
`warning: systemd-sysvcompat-239.0-2 is up to date -- skipping`
`warning: tar-1.30-1 is up to date -- skipping`
`warning: texinfo-6.5-1 is up to date -- skipping`
`warning: usbutils-010-1 is up to date -- skipping`
`warning: util-linux-2.32.1-2 is up to date -- skipping`
`warning: vi-1:070224-3 is up to date -- skipping`
`warning: which-2.21-2 is up to date -- skipping`
`warning: xfsprogs-4.17.0-1 is up to date -- skipping`
`warning: file-5.33-3 is up to date -- skipping`
`warning: groff-1.22.3-7 is up to date -- skipping`
`warning: syslinux-6.03-11 is up to date -- skipping`
`warning: util-linux-2.32.1-2 is up to date -- skipping`
`error: target not found: speedtouch`
`error: target not found: zd1211-firmware`
`error: target not found: pulseaudio-gconf`
`warning: linux-4.17.13.arch1-1 is up to date -- skipping`
`warning: archlinux-keyring-20180808-1 is up to date -- skipping`
`warning: pacman-5.1.1-1 is up to date -- skipping`
`warning: pacman-mirrorlist-20180710-1 is up to date -- skipping`
`error: target not found: js`
`error: target not found: js38`
`warning: json-c-0.13.1-1 is up to date -- skipping`
`warning: skipping target: hicolor-icon-theme`
`warning: bzip2-1.0.6-7 is up to date -- skipping`
`warning: skipping target: hicolor-icon-theme`
`warning: zsh-5.5.1-2 is up to date -- skipping`
`warning: haveged-1.9.2-1 is up to date -- skipping`
`warning: skipping target: dnsmasq`
`warning: skipping target: gtk3`
`warning: skipping target: xf86-video-nouveau`
`warning: skipping target: xf86-video-vesa`
`warning: skipping target: xorgproto`
`==> ERROR: Failed to install packages to new root`

I tried to find the reason for this error but I've been unable to solve it so far.

**Comment by Portergos** [comment]
Hi!
Thank you very much for your compliment and feedback.

Also sorry for the late response. That's a common error, it happens whenever a package is removed from one of the repositories. Those last months some packages were removed from Archlinux.

To fix that, all you have to do is open the file `packages.both` with sudo permission and remove the packages from the list. 

In your case 
error: target not found: pcmciautils
error: target not found: speedtouch
error: target not found: zd1211-firmware
error: target not found: pulseaudio-gconf
error: target not found: speedtouch
error: target not found: zd1211-firmware
error: target not found: pulseaudio-gconf
error: target not found: js
error: target not found: js38

You can remove them or comment them with `#`
Then save the file and build again.

OBS: I haven't updated the new portergos build system to github, but since you're forking and starting your own system that won't be a problem.

Cheers!
