### ISSUE TITLE
failed retrieving file 'portergos.db' from github.com

### ISSUE THREAD

**Issue by 0pcom** [Portergos/Fork-Portergos-iso#2]
I have only just now made another attempt at forking.

The system I'm doing this on is the August ISO release which has been installed to disk (not run live)

I installed archiso and ran the build.sh script as instructed; the following results:

[user@host Fork-Portergos-iso-64bits]$ sudo ./build.sh -v
[sudo] password for user: 

[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   init
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work/x86_64
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:        Pacman config file:   work/pacman.conf

[mkarchiso] INFO: Installing packages to 'work/x86_64/airootfs/'...
==> Creating install root at work/x86_64/airootfs
==> Installing packages to work/x86_64/airootfs
:: Synchronizing package databases...
error: failed retrieving file 'portergos.db' from github.com : The requested URL returned error: 404
error: failed retrieving file 'portergos.db' from sourceforge.net : The requested URL returned error: 404
error: failed to update portergos (unexpected error)
 antergos                 167.4 KiB  2.04M/s 00:00 [######################] 100%
 core is up to date
 extra                   1635.4 KiB  1721K/s 00:01 [######################] 100%
 community                  4.6 MiB  7.24M/s 00:01 [######################] 100%
 multilib`                 172.9 KiB  8.44M/s 00:00 [######################] 100%
error: failed to synchronize all databases
==> ERROR: Failed to install packages to new root
`

All I could think of was to run:
sudo pacman -Syu

 doesn't that sync the database for my installed system?
The system is up to date...

:: Synchronizing package databases...
 portergos_64 is up to date
 portergos_any is up to date
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do

I see it's the portergos_64 and portergos_any database when I run the update, not portergos.db. These may not even be the same thing. I couldn't find reference to portergos.db in build.sh.

I'm really trying to figure this out, It's just stumping me.
Thanks for your help.

**Comment by Portergos** [comment]
I uploaded the latest version (from august 2018) to the repo, please try it. https://github.com/Portergos/Fork-Portergos-iso-64bits
The old version is still using the old repository (no longer in use)

**Comment by 0pcom** [comment]
It gets almost to the end now and errors out like this:

Generating locales...
  en_US.UTF-8... done
Generation complete.
id: 'liveuser': no such user
chmod: cannot access '/media': No such file or directory

there _is_ a /media directory, so I tried making a user called liveuser to no effect.

I assume this would work on the actual live system, but that slightly complicates installation.

**Comment by 0pcom** [comment]
moving this to a new issue since it's different now from the original one
