### ISSUE TITLE
Missing /media directory interrupts build

### ISSUE THREAD

**Issue by 0pcom** [Portergos/Fork-Portergos-iso#3]
Hello again, hope you are well.

I have not resolved what is reference in the issue [https://github.com/Portergos/Fork-Portergos-iso-64bits/issues/2#issuecomment-429556479](https://github.com/Portergos/Fork-Portergos-iso-64bits/issues/2#issuecomment-429556479)

I am using an installed system of the August release of Portergos to attempt this:

`git clone https://github.com/Portergos/Fork-Portergos-iso-64bits.git`
`sudo ./build.sh -v`

Which errors out with the following:

```
==> Image generation successful
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20282  100 20282    0     0  22535      0 --:--:-- --:--:-- --:--:-- 22510

[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   run
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work/x86_64
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:               Run command:   /root/customize_airootfs.sh

==> WARNING: work/x86_64/airootfs is not a mountpoint. This may have undesirable side effects.
Generating locales...
  en_US.UTF-8... done
Generation complete.
id: 'liveuser': no such user
chmod: cannot access '/media': No such file or directory
```

I have tried making a user called liveuser; giving them sudo privelages, and from that user running the same:
`git clone https://github.com/Portergos/Fork-Portergos-iso-64bits.git`
`sudo ./build.sh -v`

The result was still the same as above.

I also tried doing this as liveuser from a live session (not installed to disk); which errors out even more quickly.

From my regular user's session, looking at the contents of
`/home/user/Fork-Portergos-iso-64bits/work/airootfs/`

I added a directory `/media` and ran again
`sudo ./build.sh -v`

```
[mkarchiso] INFO: Done! | 2.1G out/portergos-2019.01.08-x86_64.iso
```

It seems to have worked. I haven't tested it yet

**Comment by Portergos** [comment]
Yes. The /media folder was added to allow easier setting shared folders when using Virtualbox.  You did the right procedure creating /media folder.
