### ISSUE TITLE
Exhausted all available authentication mechanisms; live system policy plugin,etc. issues

### ISSUE THREAD

**Issue by 0pcom** [Portergos/Fork-Portergos-iso#4]
In testing the ISO I created from fork-portergos-iso-64bits without modifying anything, I encountered the following errors in the live system:

-upon starting xfce session, there is an immediate pop-up error message `Exhausted all available authentication mechanisms (tried: EXTRENAL) (available:EXTERNAL)`
-sudo doesn't work `unable to stat /etc/sudoers: permission denied`
-`unable to initialize policy plugin`
-can't shutdown or logoff back to the menu / terminal line
-networkmanager doesn't work

**Comment by Portergos** [comment]
Hi! Yes you're right there is an issue with permissions when downloading from github and building the iso. You can fix it with the script bellow ( create an empty file, name it "fix_permissions", add it to the same folder as "build.sh" and make it executable with `chmod +x fix_permissions` then run the script:


#!/bin/bash
chmod 700 ./airootfs/root
chmod -R 755 ./airootfs/etc/sudoers.d
chmod 755 ./airootfs/etc/sudoers.d
chmod 440 ./airootfs/etc/sudoers.d/g_wheel
chmod 644 ./airootfs/etc/systemd/system/*.service
chown 0 ./airootfs/etc/sudoers.d
chown 0 ./airootfs/etc/sudoers.d/g_wheel
chown root:root ./airootfs/etc/sudoers.d
chown root:root ./airootfs/etc/sudoers.d/g_wheel
chmod 755 ./airootfs/etc

**Comment by 0pcom** [comment]
Tested & it works now, thanks!

I was scared something had happened to you when I didn't hear from you for so long; glad you are still around & hope all is well.
