### ISSUE TITLE
"install bootloader" takes longer than "install base packages"

### ISSUE THREAD

**Issue by 0pcom** [Portergos/Fork-Portergos-iso#5]
When I build portergos (without modifying fork-portergos-iso); boot the ISO, & run through the installer, it tends to hang at Grub-install.

**Comment by Portergos** [comment]
Hi!
I can't reproduce it here. Maybe it's just taking too long, specially if you have manny partitions and more than one hard disk.

**Comment by 0pcom** [comment]
I read that it was a grub bug from having many hard disks, sorry
